- id: '1534974198409'
  alias: Configure Entities on Startup
  hide_entity: true
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: switch.flux
    service: switch.turn_on
