title: Home
views:
  - title: Overview
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: /local/Living Room@2x.png
            entities:
              - media_player.living_room
              - light.ge_dimmer_level_living_room
              - light.ge_dimmer_level_dining_nook
              - binary_sensor.living_room_window
              - binary_sensor.dome_motion_detector_living_room_sensor
          - type: horizontal-stack
            cards:
              - type: weather-forecast
                entity: weather.dark_sky
              - type: picture-glance
                image: /local/Bedroom@2x.png
                entities:
                  - light.ge_dimmer_level_bedroom
                  - binary_sensor.bedroom_window
