title: Home
views:
  - !include lovelace/view-overview.yaml
  - !include lovelace/view-living-room-media.yaml
  - !include lovelace/view-lights.yaml
  - title: Control Panel
    path: cp
    icon: mdi:monitor-dashboard
    cards:
      - type: custom:tracker-card
        title: Updates
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

resources:
  - url: /customcards/auto-entities.js
    type: js
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/card-modder.js
    type: js
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/custom-lovelace/compact-custom-header/compact-custom-header.js
    type: module
  - url: /customcards/fold-entity-row.js
    type: js
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/slider-entity-row.js
    type: js
  - url: /customcards/time-input-row.js
    type: js
  - url: /customcards/text-element.js
    type: js
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/useful-markdown-card.js
    type: js
  - url: /customcards/custom-lovelace/monster-card/monster-card.js
    type: js
