# We want some entities to be on by default after a HA restart, but HA typically
# defaults virtual entities to "off", so we explicitly turn them on here.
- alias: Configure Entities to be On at Startup
  hide_entity: true
  trigger:
    - event: start
      platform: homeassistant
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.flux

# HomeKit purges information for entities that are (from its perspective)
# removed. That means that, should HomeKit start before ZWave finishes
# intitializing, HomeKit will forget and remove any ZWave entities it had
# configured. This is a pain, so we make sure ZWave is ready before starting
# HomeKit. This causes a bit of a delay before HomeKit access is available, but
# it avoids obliterating all HomeKit config just because the ZWave component
# took a few milliseconds too long today.
# - alias: Start HomeKit
#   hide_entity: true
#   trigger:
#     - platform: event
#       event_type: zwave.network_ready
#     - platform: event
#       event_type: zwave.network_complete
#   action:
#     - service: homekit.start
