- alias: Living Room - Lighting - Movie Night On
  trigger:
    - platform: template
      value_template: >-
        {{ is_state_attr('media_player.living_room', 'source', 'Netflix') }}
    - platform: template
      value_template: >-
        {{ is_state('media_player.living_room', 'Blu-ray Player') }}
  condition:
    - condition: template
      value_template: >-
        {{ state_attr('sun.sun', 'elevation') < 4 }}
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.movie_night

- alias: Living Room - Lighting - Movie Night Off
  trigger:
    - platform: template
      value_template: >-
        {{ 
          not is_state_attr('media_player.living_room', 'source', 'Netflix') and
          not is_state('media_player.living_room', 'Blu-ray Player')
        }}
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >-
          {{ state_attr('sun.sun', 'elevation') < 4 }}
      - condition: or
        conditions:
          - condition: state
            entity_id: light.ge_jasco_wall_dimmer_dining_nook_level
            state: "on"
          - condition: state
            entity_id: light.ge_jasco_wall_dimmer_living_room_level
            state: "on"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.evening__living_room

- alias: Living Room - Media - Xbox Auto-On
  trigger:
    - platform: template
      value_template: >-
        {{ is_state_attr('media_player.living_room', 'source', 'Xbox One') }}
  action:
    - service: shell_command.xbox_one_living_room_wol

- alias: Living Room - Media - Select Xbox Input
  trigger:
    - platform: state
      entity_id: sensor.xbox_live_ben
      from: "offline"
  condition:
    - condition: template
      value_template: >-
        {{ not is_state('sensor.xbox_live_ben', 'unavailable') }}
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.living_room
    - delay:
        seconds: 1
    - service: media_player.select_source
      data:
        entity_id: media_player.living_room
        source: Xbox One
